[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal.family = "CaskaydiaMono Nerd Font"
size = 16

[window]
opacity = 0.95
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
decorations = "None"
